export const projectsArray = [
  {
    title: "PIBA Foundation",
    technologies: "MERN: MongoDB, Express.js, React, Node.js, GraphQL. Backend: Heroku, Frontend: Netlify",
    image: "https://i.imgur.com/mTW7rGB.png",
    link: "https://github.com/joshpled/pibafoundation",
    demo: "https://pibaadmindash.netlify.app/auth/login",
    type: "job",
  },
  {
    title: "First Choice Leadership",
    technologies: "React, Bootstrap, Firebase for Authentication",
    image: "https://i.imgur.com/POuQEoc.jpeg",
    link: "https://github.com/joshpled/firstchoice-leadership",
    demo: "https://firstchoiceleadership.netlify.app/home/landing",
    type: "job",
  },
  {
    title: "ToDo in Vue",
    technologies: "Vue",
    image: "https://i.imgur.com/kyGeCt6.png",
    link: "https://github.com/joshpled/Vue-ToDoList",
    demo: "https://joshpled.github.io/Vue-ToDoList/",
    type: "personal",
  },
  {
    title: "TIC-TAC-TOE",
    technologies: "Create-React-App, React, Bootstrap",
    image: "https://i.imgur.com/GVnUsUX.png",
    link: "https://github.com/joshpled/tic-tac-toe",
    demo: "https://joshpled.github.io/tic-tac-toe/",
    type: "personal",
  },
  {
    title: "Tamapuri",
    technologies: "Create-React-App, React, Bootstrap, Ruby on Rails Backend; Deployed to Heroku, Frontend: Netlify ",
    image: "https://i.imgur.com/X8QDe4h.png",
    link: "https://github.com/joshpled/Tamapuri2.0",
    demo: "https://tamapuri.netlify.app/",
    type: "school",
  },
];
